# Generated by Django 2.1.2 on 2020-12-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_remove_profile_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('book_picture', models.ImageField(blank=True, null=True, upload_to='libro/pictures')),
                ('cantidad_existente', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('autor_id', models.ManyToManyField(blank=True, to='libro.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('libro_prestado', models.BooleanField(default=True)),
                ('libro_entregado', models.BooleanField(default=False)),
                ('entregado_date', models.DateTimeField(blank=True, null=True)),
                ('libro_id', models.ManyToManyField(to='libro.Libro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
            ],
        ),
    ]
