# Generated by Django 2.1.2 on 2021-02-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_profile_user_picture'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='book_picture',
        ),
        migrations.AddField(
            model_name='reservation',
            name='libro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.Libro'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile'),
        ),
    ]
