# Generated by Django 2.1.2 on 2020-12-19 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_picture',
        ),
    ]
